/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CreateEntityMenu: typeof import('./src/components/CreateEntityMenu.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    ImageItem: typeof import('@/modules/entities/ImageItem.vue')['default']
    ImageMoveMenu: typeof import('./src/components/editEntityMenu/ImageMoveMenu.vue')['default']
    ImageSizeMenu: typeof import('./src/components/editEntityMenu/ImageSizeMenu.vue')['default']
    ImageStateMenu: typeof import('./src/components/editEntityMenu/ImageStateMenu.vue')['default']
    LogoAndLabel: typeof import('./src/components/LogoAndLabel.vue')['default']
    MoveImageMenu: typeof import('./src/components/editEntityMenu/image/MoveImageMenu.vue')['default']
    MoveMenu: typeof import('./src/components/editEntityMenu/text/MoveMenu.vue')['default']
    MoveTextMenu: typeof import('./src/components/editEntityMenu/text/MoveTextMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    StateImageMenu: typeof import('./src/components/editEntityMenu/image/StateImageMenu.vue')['default']
    StateMenu: typeof import('./src/components/editEntityMenu/text/StateMenu.vue')['default']
    StateTextMenu: typeof import('./src/components/editEntityMenu/text/StateTextMenu.vue')['default']
    TextItem: typeof import('@/modules/entities/TextItem.vue')['default']
    TextMoveMenu: typeof import('./src/components/editEntityMenu/TextMoveMenu.vue')['default']
    TextStateMenu: typeof import('./src/components/editEntityMenu/TextStateMenu.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Tree: typeof import('primevue/tree')['default']
    UserInfoHeaderWithSettings: typeof import('./src/components/UserInfoHeaderWithSettings.vue')['default']
  }
}
