/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CreateEntityMenu: typeof import('./src/components/CreateEntityMenu.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EditImageEntityMenu: typeof import('./src/components/EditImageEntityMenu.vue')['default']
    EditTextEntityMenu: typeof import('./src/components/EditTextEntityMenu.vue')['default']
    ImageItem: typeof import('./src/components/entities/ImageItem.vue')['default']
    LogoAndLabel: typeof import('./src/components/LogoAndLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    TextItem: typeof import('./src/components/entities/TextItem.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Tree: typeof import('primevue/tree')['default']
    UserInfoHeaderWithSettings: typeof import('./src/components/UserInfoHeaderWithSettings.vue')['default']
  }
}
