/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    AuthorizationForm: typeof import('./../modules/authorization/AuthorizationForm.vue')['default']
    BaseLoader: typeof import('./../shared/BaseLoader.vue')['default']
    ChangeSheetsModal: typeof import('./../modules/settings/ChangeSheetsModal.vue')['default']
    ConfirmMail: typeof import('./../pages/authorization/ConfirmMail.vue')['default']
    CreateEntityMenu: typeof import('./../components/common/CreateEntityMenu.vue')['default']
    CropImageModal: typeof import('./../modules/common/CropImageModal.vue')['default']
    DeleteEntityConfirmModal: typeof import('./../modules/common/DeleteEntityConfirmModal.vue')['default']
    DividerEntity: typeof import('./../modules/sheets/entities/items/DividerEntity.vue')['default']
    DividerSettings: typeof import('./../components/sheets/entities/settings/DividerSettings.vue')['default']
    DividerSettingsList: typeof import('./../components/sheets/entities/settings/lists/DividerSettingsList.vue')['default']
    EntitiesList: typeof import('./../modules/sheets/entities/EntitiesList.vue')['default']
    EntityItem: typeof import('./../modules/sheets/entities/EntityItem.vue')['default']
    EntityPositionSettings: typeof import('./../components/sheets/entities/settings/EntityPositionSettings.vue')['default']
    EntitySettingsModalHeader: typeof import('./../components/sheets/entities/settings/common/EntitySettingsModalHeader.vue')['default']
    EntityTitle: typeof import('./../components/sheets/entities/share/EntityTitle.vue')['default']
    ImageEntity: typeof import('./../modules/sheets/entities/items/ImageEntity.vue')['default']
    ImageEntityImageWithText: typeof import('./../components/sheets/entities/content/ImageEntityImageWithText.vue')['default']
    ImageSettings: typeof import('./../components/sheets/entities/settings/ImageSettings.vue')['default']
    ImageSettingsEntityBlock: typeof import('./../components/sheets/entities/settings/entityBlock/ImageSettingsEntityBlock.vue')['default']
    ImageSettingsList: typeof import('./../components/sheets/entities/settings/lists/ImageSettingsList.vue')['default']
    ParagraphEntity: typeof import('./../modules/sheets/entities/items/ParagraphEntity.vue')['default']
    ParagraphSettings: typeof import('./../components/sheets/entities/settings/ParagraphSettings.vue')['default']
    ParagraphSettingsList: typeof import('./../components/sheets/entities/settings/lists/ParagraphSettingsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../pages/settings/Settings.vue')['default']
    SettingsSheetsSection: typeof import('./../modules/settings/SettingsSheetsSection.vue')['default']
    SheetBackgroundMenu: typeof import('./../modules/sheets/SheetBackgroundMenu.vue')['default']
    SheetHeader: typeof import('./../modules/sheets/SheetHeader.vue')['default']
    SheetPage: typeof import('./../pages/sheets/SheetPage.vue')['default']
    SheetPageContent: typeof import('./../modules/sheets/SheetPageContent.vue')['default']
    SheetTelegramSection: typeof import('./../modules/sheets/SheetTelegramSection.vue')['default']
    SidebarMenu: typeof import('./../modules/common/SidebarMenu.vue')['default']
    SidebarMenuButton: typeof import('./../components/common/SidebarMenuButton.vue')['default']
    SignIn: typeof import('./../pages/authorization/SignIn.vue')['default']
    SignUp: typeof import('./../pages/authorization/SignUp.vue')['default']
    SignUpCredentials: typeof import('./../components/authorization/SignUpCredentials.vue')['default']
    TableEntity: typeof import('./../modules/sheets/entities/items/TableEntity.vue')['default']
  }
}
