/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BaseDivider: typeof import('./../shared/BaseDivider.vue')['default']
    BaseLoader: typeof import('./../shared/BaseLoader.vue')['default']
    BaseSidebarMenu: typeof import('./../modules/BaseSidebarMenu.vue')['default']
    Button: typeof import('primevue/button')['default']
    CreateEntityMenu: typeof import('./../components/CreateEntityMenu.vue')['default']
    CropImageModal: typeof import('./../modules/CropImageModal.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    DividerItem: typeof import('./../modules/entities/DividerItem.vue')['default']
    DividerMenu: typeof import('./../modules/entities/menu/DividerMenu.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EntitiesList: typeof import('./../modules/entities/EntitiesList.vue')['default']
    EntityItem: typeof import('./../modules/entities/EntityItem.vue')['default']
    EntityTitle: typeof import('./../components/entities/share/EntityTitle.vue')['default']
    HomePage: typeof import('./../pages/HomePage.vue')['default']
    ImageItem: typeof import('./../modules/entities/ImageItem.vue')['default']
    ImageMenu: typeof import('./../modules/entities/menu/ImageMenu.vue')['default']
    ImagePositionMenu: typeof import('./../components/entities/image/ImagePositionMenu.vue')['default']
    ImageSizeMenu: typeof import('./../components/entities/image/ImageSizeMenu.vue')['default']
    ImageStateMenu: typeof import('./../components/entities/image/ImageStateMenu.vue')['default']
    LogoAndLabel: typeof import('./../components/LogoAndLabel.vue')['default']
    page: typeof import('./../modules/Home page.vue')['default']
    PageBackgroundMenu: typeof import('./../modules/PageBackgroundMenu.vue')['default']
    PageHeader: typeof import('./../modules/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SheetPage: typeof import('./../pages/[uuid]/SheetPage.vue')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    TelegramSection: typeof import('./../modules/TelegramSection.vue')['default']
    TextFontMenu: typeof import('./../components/entities/share/TextFontMenu.vue')['default']
    TextItem: typeof import('./../modules/entities/TextItem.vue')['default']
    TextMenu: typeof import('./../modules/entities/menu/TextMenu.vue')['default']
    TextPositionMenu: typeof import('./../components/entities/text/TextPositionMenu.vue')['default']
    TextStateMenu: typeof import('./../components/entities/text/TextStateMenu.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Tree: typeof import('primevue/tree')['default']
    UserInfoHeaderWithSettings: typeof import('./../components/UserInfoHeaderWithSettings.vue')['default']
  }
}
