/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BaseDivider: typeof import('./../shared/BaseDivider.vue')['default']
    BaseSidebarMenu: typeof import('./../modules/BaseSidebarMenu.vue')['default']
    Button: typeof import('primevue/button')['default']
    CreateEntityMenu: typeof import('./../components/CreateEntityMenu.vue')['default']
    CropImageModal: typeof import('./../modules/CropImageModal.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EntityItem: typeof import('./../modules/EntityItem.vue')['default']
    HomePage: typeof import('./../pages/HomePage.vue')['default']
    ImageItem: typeof import('./../modules/entities/ImageItem.vue')['default']
    ImagePositionMenu: typeof import('./../components/editEntityMenu/ImagePositionMenu.vue')['default']
    ImageSizeMenu: typeof import('./../components/editEntityMenu/ImageSizeMenu.vue')['default']
    ImageStateMenu: typeof import('./../components/editEntityMenu/ImageStateMenu.vue')['default']
    LogoAndLabel: typeof import('./../components/LogoAndLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SheetPage: typeof import('./../pages/[uuid]/SheetPage.vue')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    TextFontMenu: typeof import('./../components/editEntityMenu/TextFontMenu.vue')['default']
    TextItem: typeof import('./../modules/entities/TextItem.vue')['default']
    TextPositionMenu: typeof import('./../components/editEntityMenu/TextPositionMenu.vue')['default']
    TextStateMenu: typeof import('./../components/editEntityMenu/TextStateMenu.vue')['default']
    Tree: typeof import('primevue/tree')['default']
    UserInfoHeaderWithSettings: typeof import('./../components/UserInfoHeaderWithSettings.vue')['default']
  }
}
